insert into trains (model, capacity) values ('Sedona', 26);
insert into trains (model, capacity) values ('A4', 75);
insert into trains (model, capacity) values ('NSX', 41);
insert into trains (model, capacity) values ('Accord', 88);
insert into trains (model, capacity) values ('Savana 1500', 37);
insert into trains (model, capacity) values ('Tracker', 1);
insert into trains (model, capacity) values ('300D', 28);
insert into trains (model, capacity) values ('Skyhawk', 80);
insert into trains (model, capacity) values ('RX', 34);
insert into trains (model, capacity) values ('C-Class', 43);
insert into trains (model, capacity) values ('Excel', 28);
insert into trains (model, capacity) values ('S10', 10);
insert into trains (model, capacity) values ('Swift', 47);
insert into trains (model, capacity) values ('Chariot', 59);
insert into trains (model, capacity) values ('Discovery', 14);
insert into trains (model, capacity) values ('Raider', 31);
insert into trains (model, capacity) values ('tC', 28);
insert into trains (model, capacity) values ('TT', 37);
insert into trains (model, capacity) values ('Acadia', 37);
insert into trains (model, capacity) values ('V70', 31);
insert into trains (model, capacity) values ('V8', 77);
insert into trains (model, capacity) values ('A3', 62);
insert into trains (model, capacity) values ('Rondo', 70);
insert into trains (model, capacity) values ('Sebring', 98);
insert into trains (model, capacity) values ('Express 1500', 62);
insert into trains (model, capacity) values ('645', 95);
insert into trains (model, capacity) values ('Cobalt SS', 8);
insert into trains (model, capacity) values ('Aerostar', 86);
insert into trains (model, capacity) values ('Park Avenue', 49);
insert into trains (model, capacity) values ('Sportage', 6);
insert into trains (model, capacity) values ('Vandura G2500', 79);
insert into trains (model, capacity) values ('W201', 47);
insert into trains (model, capacity) values ('SL-Class', 68);
insert into trains (model, capacity) values ('1500', 79);
insert into trains (model, capacity) values ('Sunbird', 48);
insert into trains (model, capacity) values ('GS', 47);
insert into trains (model, capacity) values ('Explorer Sport Trac', 82);
insert into trains (model, capacity) values ('300ZX', 63);
insert into trains (model, capacity) values ('Town Car', 78);
insert into trains (model, capacity) values ('XK', 24);
insert into trains (model, capacity) values ('Silhouette', 80);
insert into trains (model, capacity) values ('Premier', 20);
insert into trains (model, capacity) values ('F150', 62);
insert into trains (model, capacity) values ('PT Cruiser', 11);
insert into trains (model, capacity) values ('Suburban 2500', 30);
insert into trains (model, capacity) values ('MR2', 66);
insert into trains (model, capacity) values ('Sierra 3500', 99);
insert into trains (model, capacity) values ('Durango', 67);
insert into trains (model, capacity) values ('Z8', 53);
insert into trains (model, capacity) values ('Fiero', 48);
insert into trains (model, capacity) values ('Sienna', 12);
insert into trains (model, capacity) values ('90', 34);
insert into trains (model, capacity) values ('xB', 2);
insert into trains (model, capacity) values ('Express 3500', 31);
insert into trains (model, capacity) values ('XLR', 96);
insert into trains (model, capacity) values ('Ram 3500', 53);
insert into trains (model, capacity) values ('HHR', 58);
insert into trains (model, capacity) values ('Pathfinder', 21);
insert into trains (model, capacity) values ('Nitro', 70);
insert into trains (model, capacity) values ('100', 6);
insert into trains (model, capacity) values ('7 Series', 89);
insert into trains (model, capacity) values ('X6', 59);
insert into trains (model, capacity) values ('G-Series G10', 29);
insert into trains (model, capacity) values ('626', 72);
insert into trains (model, capacity) values ('Escalade ESV', 29);
insert into trains (model, capacity) values ('4Runner', 13);
insert into trains (model, capacity) values ('Tundra', 32);
insert into trains (model, capacity) values ('Thunderbird', 70);
insert into trains (model, capacity) values ('Reno', 74);
insert into trains (model, capacity) values ('Precis', 16);
insert into trains (model, capacity) values ('Kizashi', 33);
insert into trains (model, capacity) values ('Probe', 79);
insert into trains (model, capacity) values ('Ram 2500', 4);
insert into trains (model, capacity) values ('Mystique', 9);
insert into trains (model, capacity) values ('Magnum', 52);
insert into trains (model, capacity) values ('Canyon', 40);
insert into trains (model, capacity) values ('Millenia', 14);
insert into trains (model, capacity) values ('Vibe', 6);
insert into trains (model, capacity) values ('Escape', 14);
insert into trains (model, capacity) values ('T100', 100);
insert into trains (model, capacity) values ('Sable', 51);
insert into trains (model, capacity) values ('Firebird Trans Am', 82);
insert into trains (model, capacity) values ('Eldorado', 19);
insert into trains (model, capacity) values ('Focus', 57);
insert into trains (model, capacity) values ('Ram', 7);
insert into trains (model, capacity) values ('Mazda6', 78);
insert into trains (model, capacity) values ('MDX', 10);
insert into trains (model, capacity) values ('90', 63);
insert into trains (model, capacity) values ('Grand Vitara', 51);
insert into trains (model, capacity) values ('Grand Vitara', 62);
insert into trains (model, capacity) values ('Probe', 37);
insert into trains (model, capacity) values ('Pathfinder', 28);
insert into trains (model, capacity) values ('Type 2', 89);
insert into trains (model, capacity) values ('9-7X', 71);
insert into trains (model, capacity) values ('Accent', 18);
insert into trains (model, capacity) values ('S-Class', 12);
insert into trains (model, capacity) values ('Express', 86);
insert into trains (model, capacity) values ('Escalade', 11);
insert into trains (model, capacity) values ('Sonata', 59);
insert into trains (model, capacity) values ('Taurus', 67);
insert into trains (model, capacity) values ('Caravan', 91);
insert into trains (model, capacity) values ('HS', 4);
insert into trains (model, capacity) values ('Voyager', 89);
insert into trains (model, capacity) values ('SL-Class', 55);
insert into trains (model, capacity) values ('Highlander', 71);
insert into trains (model, capacity) values ('RL', 5);
insert into trains (model, capacity) values ('GTI', 84);
insert into trains (model, capacity) values ('S-Class', 54);
insert into trains (model, capacity) values ('SX4', 49);
insert into trains (model, capacity) values ('Sable', 76);
insert into trains (model, capacity) values ('Odyssey', 51);
insert into trains (model, capacity) values ('Azera', 18);
insert into trains (model, capacity) values ('Golf', 59);
insert into trains (model, capacity) values ('Tacoma', 50);
insert into trains (model, capacity) values ('Leone', 80);
insert into trains (model, capacity) values ('E-Series', 99);
insert into trains (model, capacity) values ('Jetta', 24);
insert into trains (model, capacity) values ('Tracker', 27);
insert into trains (model, capacity) values ('GTO', 40);
insert into trains (model, capacity) values ('Yukon XL 2500', 49);
insert into trains (model, capacity) values ('Camry Hybrid', 75);
insert into trains (model, capacity) values ('Sportage', 40);
insert into trains (model, capacity) values ('LTD Crown Victoria', 40);
insert into trains (model, capacity) values ('A4', 6);
insert into trains (model, capacity) values ('9-5', 40);
insert into trains (model, capacity) values ('Ram Van B250', 96);
insert into trains (model, capacity) values ('600SEL', 50);
insert into trains (model, capacity) values ('Astro', 53);
insert into trains (model, capacity) values ('M5', 61);
insert into trains (model, capacity) values ('A4', 85);
insert into trains (model, capacity) values ('Express 2500', 87);
insert into trains (model, capacity) values ('Vision', 59);
insert into trains (model, capacity) values ('A4', 8);
insert into trains (model, capacity) values ('240SX', 48);
insert into trains (model, capacity) values ('Eldorado', 94);
insert into trains (model, capacity) values ('Mountaineer', 35);
insert into trains (model, capacity) values ('9-7X', 28);
insert into trains (model, capacity) values ('Altima', 57);
insert into trains (model, capacity) values ('Dakota', 31);
insert into trains (model, capacity) values ('Arnage', 79);
insert into trains (model, capacity) values ('CT', 83);
insert into trains (model, capacity) values ('Hombre', 85);
insert into trains (model, capacity) values ('Corolla', 6);
insert into trains (model, capacity) values ('G-Class', 64);
insert into trains (model, capacity) values ('Sundance', 9);
insert into trains (model, capacity) values ('Outlander Sport', 26);
insert into trains (model, capacity) values ('Lumina', 54);
insert into trains (model, capacity) values ('Montero', 1);
insert into trains (model, capacity) values ('Swift', 74);
insert into trains (model, capacity) values ('Esteem', 97);
insert into trains (model, capacity) values ('Jetta', 79);
insert into trains (model, capacity) values ('Impala', 69);
insert into trains (model, capacity) values ('944', 94);
insert into trains (model, capacity) values ('E150', 7);
insert into trains (model, capacity) values ('Topaz', 73);
insert into trains (model, capacity) values ('Express 1500', 46);
insert into trains (model, capacity) values ('F350', 72);
insert into trains (model, capacity) values ('240SX', 66);
insert into trains (model, capacity) values ('Montero Sport', 53);
insert into trains (model, capacity) values ('Dakota', 18);
insert into trains (model, capacity) values ('Outback', 5);
insert into trains (model, capacity) values ('Escalade', 5);
insert into trains (model, capacity) values ('Rogue', 58);
insert into trains (model, capacity) values ('Z8', 80);
insert into trains (model, capacity) values ('XF', 69);
insert into trains (model, capacity) values ('W201', 81);
insert into trains (model, capacity) values ('Samurai', 43);
insert into trains (model, capacity) values ('Tundra', 94);
insert into trains (model, capacity) values ('Express 1500', 67);
insert into trains (model, capacity) values ('Taurus', 67);
insert into trains (model, capacity) values ('Camaro', 9);
insert into trains (model, capacity) values ('DeVille', 25);
insert into trains (model, capacity) values ('Silverado 1500', 9);
insert into trains (model, capacity) values ('DeVille', 62);
insert into trains (model, capacity) values ('Edge', 94);
insert into trains (model, capacity) values ('Spyder', 2);
insert into trains (model, capacity) values ('Durango', 94);
insert into trains (model, capacity) values ('F250', 37);
insert into trains (model, capacity) values ('G6', 42);
insert into trains (model, capacity) values ('i-Series', 47);
insert into trains (model, capacity) values ('Pajero', 42);
insert into trains (model, capacity) values ('626', 30);
insert into trains (model, capacity) values ('626', 55);
insert into trains (model, capacity) values ('Sportage', 72);
insert into trains (model, capacity) values ('SX4', 82);
insert into trains (model, capacity) values ('300CE', 2);
insert into trains (model, capacity) values ('LaCrosse', 51);
insert into trains (model, capacity) values ('Chariot', 18);
insert into trains (model, capacity) values ('Alcyone SVX', 26);
insert into trains (model, capacity) values ('Tempest', 26);
insert into trains (model, capacity) values ('Entourage', 11);
insert into trains (model, capacity) values ('Camaro', 47);
insert into trains (model, capacity) values ('Rogue', 54);
insert into trains (model, capacity) values ('GTI', 93);
insert into trains (model, capacity) values ('F-Series Super Duty', 99);
insert into trains (model, capacity) values ('Yaris', 58);
insert into trains (model, capacity) values ('Savana 1500', 12);
insert into trains (model, capacity) values ('Spirit', 52);
insert into trains (model, capacity) values ('M', 13);
insert into trains (model, capacity) values ('E350', 93);
insert into trains (model, capacity) values ('Yukon XL 2500', 21);
insert into trains (model, capacity) values ('Sixty Special', 54);
insert into trains (model, capacity) values ('Cayenne', 18);
insert into trains (model, capacity) values ('MPV', 1);
insert into trains (model, capacity) values ('Montero', 77);
insert into trains (model, capacity) values ('Fit', 14);
insert into trains (model, capacity) values ('Sable', 30);
insert into trains (model, capacity) values ('GS', 14);
insert into trains (model, capacity) values ('Golf', 17);
insert into trains (model, capacity) values ('Avenger', 65);
insert into trains (model, capacity) values ('Taurus', 84);
insert into trains (model, capacity) values ('Suburban 1500', 94);
insert into trains (model, capacity) values ('F-Series', 27);
insert into trains (model, capacity) values ('Country', 71);
insert into trains (model, capacity) values ('911', 6);
insert into trains (model, capacity) values ('XC90', 54);
insert into trains (model, capacity) values ('9-5', 86);
insert into trains (model, capacity) values ('5000S', 54);
insert into trains (model, capacity) values ('Caravan', 30);
insert into trains (model, capacity) values ('Land Cruiser', 5);
insert into trains (model, capacity) values ('Loyale', 95);
insert into trains (model, capacity) values ('Amanti', 17);
insert into trains (model, capacity) values ('S5', 60);
insert into trains (model, capacity) values ('Pilot', 11);
insert into trains (model, capacity) values ('928', 98);
insert into trains (model, capacity) values ('Mighty Max Macro', 18);
insert into trains (model, capacity) values ('QX', 14);
insert into trains (model, capacity) values ('E350', 64);
insert into trains (model, capacity) values ('90', 53);
insert into trains (model, capacity) values ('Cooper Clubman', 68);
insert into trains (model, capacity) values ('SL-Class', 63);
insert into trains (model, capacity) values ('430', 13);
insert into trains (model, capacity) values ('Express 2500', 72);
insert into trains (model, capacity) values ('Explorer', 22);
insert into trains (model, capacity) values ('911', 42);
insert into trains (model, capacity) values ('LS', 16);
insert into trains (model, capacity) values ('Q', 43);
insert into trains (model, capacity) values ('Ram Van 1500', 60);
insert into trains (model, capacity) values ('Expedition', 99);
insert into trains (model, capacity) values ('R32', 36);
insert into trains (model, capacity) values ('LTD Crown Victoria', 97);
insert into trains (model, capacity) values ('Equinox', 85);
insert into trains (model, capacity) values ('SLK-Class', 38);
insert into trains (model, capacity) values ('E250', 77);
insert into trains (model, capacity) values ('928', 62);
insert into trains (model, capacity) values ('V40', 35);
insert into trains (model, capacity) values ('100', 49);
insert into trains (model, capacity) values ('Tundra', 44);
insert into trains (model, capacity) values ('900', 45);
insert into trains (model, capacity) values ('1500', 58);
insert into trains (model, capacity) values ('Cherokee', 68);
insert into trains (model, capacity) values ('C8 Spyder', 36);
insert into trains (model, capacity) values ('Sierra 1500', 26);
insert into trains (model, capacity) values ('Sidekick', 15);
insert into trains (model, capacity) values ('Titan', 56);
insert into trains (model, capacity) values ('Yukon', 64);
insert into trains (model, capacity) values ('Exige', 28);
insert into trains (model, capacity) values ('G', 19);
insert into trains (model, capacity) values ('del Sol', 86);
insert into trains (model, capacity) values ('A5', 45);
insert into trains (model, capacity) values ('Precis', 93);
insert into trains (model, capacity) values ('STS', 45);
insert into trains (model, capacity) values ('Fleetwood', 43);
insert into trains (model, capacity) values ('Tundra', 52);
insert into trains (model, capacity) values ('Ram Van B350', 17);
insert into trains (model, capacity) values ('S-Class', 92);
insert into trains (model, capacity) values ('Camaro', 97);
insert into trains (model, capacity) values ('E150', 9);
insert into trains (model, capacity) values ('S40', 2);
insert into trains (model, capacity) values ('Ranger', 17);
insert into trains (model, capacity) values ('Carrera GT', 6);
insert into trains (model, capacity) values ('S80', 93);
insert into trains (model, capacity) values ('Bonneville', 9);
insert into trains (model, capacity) values ('6 Series', 58);
insert into trains (model, capacity) values ('Esteem', 65);
insert into trains (model, capacity) values ('Suburban 1500', 97);
insert into trains (model, capacity) values ('Sebring', 69);
insert into trains (model, capacity) values ('SLR McLaren', 67);
insert into trains (model, capacity) values ('MR2', 92);
insert into trains (model, capacity) values ('Prizm', 88);
insert into trains (model, capacity) values ('1 Series', 54);
insert into trains (model, capacity) values ('Grand Caravan', 67);
insert into trains (model, capacity) values ('Bonneville', 87);
insert into trains (model, capacity) values ('Elantra', 92);
insert into trains (model, capacity) values ('Accent', 41);
insert into trains (model, capacity) values ('Impreza', 38);
insert into trains (model, capacity) values ('Altima', 64);
insert into trains (model, capacity) values ('Caravan', 30);
insert into trains (model, capacity) values ('Laser', 27);
insert into trains (model, capacity) values ('Montero Sport', 35);
insert into trains (model, capacity) values ('Sierra 2500', 71);
insert into trains (model, capacity) values ('RX', 15);
insert into trains (model, capacity) values ('Capri', 21);
insert into trains (model, capacity) values ('Grand Prix', 88);
insert into trains (model, capacity) values ('Sorento', 95);
insert into trains (model, capacity) values ('Aspen', 26);
insert into trains (model, capacity) values ('TSX', 47);
insert into trains (model, capacity) values ('Neon', 98);
insert into trains (model, capacity) values ('Monte Carlo', 64);
insert into trains (model, capacity) values ('Accord', 7);
insert into trains (model, capacity) values ('Grand Prix', 100);
insert into trains (model, capacity) values ('Cavalier', 36);
insert into trains (model, capacity) values ('Tempo', 9);
insert into trains (model, capacity) values ('Grand Caravan', 42);
insert into trains (model, capacity) values ('Cobalt', 72);
insert into trains (model, capacity) values ('Echo', 36);
insert into trains (model, capacity) values ('Xtra', 21);
insert into trains (model, capacity) values ('RX-7', 47);
insert into trains (model, capacity) values ('Edge', 44);
insert into trains (model, capacity) values ('HHR', 78);
insert into trains (model, capacity) values ('Forester', 35);
insert into trains (model, capacity) values ('Land Cruiser', 53);
insert into trains (model, capacity) values ('Astro', 84);
insert into trains (model, capacity) values ('Eclipse', 15);
insert into trains (model, capacity) values ('6000', 23);
insert into trains (model, capacity) values ('Ascender', 47);
insert into trains (model, capacity) values ('Tracker', 1);
insert into trains (model, capacity) values ('164', 27);
insert into trains (model, capacity) values ('Neon', 15);
insert into trains (model, capacity) values ('GTO', 81);
insert into trains (model, capacity) values ('Sportage', 14);
insert into trains (model, capacity) values ('Navigator', 61);
insert into trains (model, capacity) values ('Lynx', 39);
insert into trains (model, capacity) values ('LS', 75);
insert into trains (model, capacity) values ('S-Class', 62);
insert into trains (model, capacity) values ('CX-7', 53);
insert into trains (model, capacity) values ('Silhouette', 5);
insert into trains (model, capacity) values ('Solara', 25);
insert into trains (model, capacity) values ('Ascender', 19);
insert into trains (model, capacity) values ('Sonata', 77);
insert into trains (model, capacity) values ('612 Scaglietti', 65);
insert into trains (model, capacity) values ('Xterra', 65);
insert into trains (model, capacity) values ('2500', 32);
insert into trains (model, capacity) values ('Echo', 88);
insert into trains (model, capacity) values ('MKX', 26);
insert into trains (model, capacity) values ('Cutlass Supreme', 10);
insert into trains (model, capacity) values ('Intrigue', 85);
insert into trains (model, capacity) values ('Grand Vitara', 22);
insert into trains (model, capacity) values ('Freelander', 54);
insert into trains (model, capacity) values ('300SL', 5);
insert into trains (model, capacity) values ('944', 18);
insert into trains (model, capacity) values ('1500 Club Coupe', 54);
insert into trains (model, capacity) values ('Tundra', 15);
insert into trains (model, capacity) values ('Century', 58);
insert into trains (model, capacity) values ('A8', 36);
insert into trains (model, capacity) values ('626', 86);
insert into trains (model, capacity) values ('SL-Class', 79);
insert into trains (model, capacity) values ('Sequoia', 22);
insert into trains (model, capacity) values ('MKZ', 42);
insert into trains (model, capacity) values ('SRX', 64);
insert into trains (model, capacity) values ('3500', 8);
insert into trains (model, capacity) values ('Escalade EXT', 34);
insert into trains (model, capacity) values ('Silverado 1500', 28);
insert into trains (model, capacity) values ('Z4 M Roadster', 23);
insert into trains (model, capacity) values ('Ram 50', 83);
insert into trains (model, capacity) values ('Prelude', 33);
insert into trains (model, capacity) values ('MX-5', 3);
insert into trains (model, capacity) values ('Riviera', 86);
insert into trains (model, capacity) values ('S6', 54);
insert into trains (model, capacity) values ('Tacoma Xtra', 26);
insert into trains (model, capacity) values ('Blazer', 48);
insert into trains (model, capacity) values ('Quattro', 40);
insert into trains (model, capacity) values ('Continental Super', 64);
insert into trains (model, capacity) values ('Caravan', 51);
insert into trains (model, capacity) values ('SLS AMG', 99);
insert into trains (model, capacity) values ('Express 3500', 81);
insert into trains (model, capacity) values ('C-Class', 39);
insert into trains (model, capacity) values ('Range Rover', 79);
insert into trains (model, capacity) values ('Prowler', 42);
insert into trains (model, capacity) values ('Camaro', 26);
insert into trains (model, capacity) values ('S4', 26);
insert into trains (model, capacity) values ('Golf', 73);
insert into trains (model, capacity) values ('Taurus', 7);
insert into trains (model, capacity) values ('LTD Crown Victoria', 77);
insert into trains (model, capacity) values ('Probe', 73);
insert into trains (model, capacity) values ('Sonoma', 43);
insert into trains (model, capacity) values ('Canyon', 7);
insert into trains (model, capacity) values ('9-3', 92);
insert into trains (model, capacity) values ('tC', 96);
insert into trains (model, capacity) values ('Sienna', 16);
insert into trains (model, capacity) values ('Tacoma', 43);
insert into trains (model, capacity) values ('Regal', 46);
insert into trains (model, capacity) values ('Mountaineer', 86);
insert into trains (model, capacity) values ('Dakota Club', 30);
insert into trains (model, capacity) values ('323', 52);
insert into trains (model, capacity) values ('Seville', 77);
insert into trains (model, capacity) values ('Truck', 20);
insert into trains (model, capacity) values ('XC70', 29);
insert into trains (model, capacity) values ('Celica', 21);
insert into trains (model, capacity) values ('Pathfinder', 64);
insert into trains (model, capacity) values ('Sedona', 40);
insert into trains (model, capacity) values ('GTI', 99);
insert into trains (model, capacity) values ('Ram 1500', 68);
insert into trains (model, capacity) values ('Quest', 76);
insert into trains (model, capacity) values ('Sprinter', 50);
insert into trains (model, capacity) values ('Xterra', 66);
insert into trains (model, capacity) values ('Range Rover', 64);
insert into trains (model, capacity) values ('Maxima', 15);
insert into trains (model, capacity) values ('Savana 1500', 52);
insert into trains (model, capacity) values ('RX-7', 56);
insert into trains (model, capacity) values ('S4', 48);
insert into trains (model, capacity) values ('F-Series', 19);
insert into trains (model, capacity) values ('Th!nk', 5);
insert into trains (model, capacity) values ('Express', 88);
insert into trains (model, capacity) values ('Malibu', 10);
insert into trains (model, capacity) values ('Venza', 90);
insert into trains (model, capacity) values ('Flex', 61);
insert into trains (model, capacity) values ('DB9', 48);
insert into trains (model, capacity) values ('Town & Country', 40);
insert into trains (model, capacity) values ('S80', 35);
insert into trains (model, capacity) values ('Mystique', 25);
insert into trains (model, capacity) values ('Century', 61);
insert into trains (model, capacity) values ('Z8', 22);
insert into trains (model, capacity) values ('Tucson', 77);
insert into trains (model, capacity) values ('Altima', 35);
insert into trains (model, capacity) values ('R32', 14);
insert into trains (model, capacity) values ('A4', 29);
insert into trains (model, capacity) values ('900', 84);
insert into trains (model, capacity) values ('J', 57);
insert into trains (model, capacity) values ('E-Series', 75);
insert into trains (model, capacity) values ('1 Series', 66);
insert into trains (model, capacity) values ('Regal', 30);
insert into trains (model, capacity) values ('Accord', 78);
insert into trains (model, capacity) values ('Precis', 100);
insert into trains (model, capacity) values ('Express 2500', 38);
insert into trains (model, capacity) values ('MX-3', 76);
insert into trains (model, capacity) values ('Mustang', 18);
insert into trains (model, capacity) values ('Mark VIII', 43);
insert into trains (model, capacity) values ('CR-V', 38);
insert into trains (model, capacity) values ('Grand Marquis', 93);
insert into trains (model, capacity) values ('Leone', 38);
insert into trains (model, capacity) values ('Tribute', 77);
insert into trains (model, capacity) values ('Swift', 1);
insert into trains (model, capacity) values ('G8', 92);
insert into trains (model, capacity) values ('Montero Sport', 75);
insert into trains (model, capacity) values ('D350 Club', 12);
insert into trains (model, capacity) values ('LS Hybrid', 76);
insert into trains (model, capacity) values ('G-Series G10', 12);
insert into trains (model, capacity) values ('XJ Series', 12);
insert into trains (model, capacity) values ('Town Car', 34);
insert into trains (model, capacity) values ('Camaro', 18);
insert into trains (model, capacity) values ('Caprice', 86);
insert into trains (model, capacity) values ('Corrado', 52);
insert into trains (model, capacity) values ('Tracker', 1);
insert into trains (model, capacity) values ('Panamera', 76);
insert into trains (model, capacity) values ('Wrangler', 1);
insert into trains (model, capacity) values ('MKS', 91);
insert into trains (model, capacity) values ('Daewoo Lacetti', 77);
insert into trains (model, capacity) values ('JUKE', 11);
insert into trains (model, capacity) values ('Caliber', 52);
insert into trains (model, capacity) values ('Chariot', 1);
insert into trains (model, capacity) values ('Tracker', 38);
insert into trains (model, capacity) values ('Cougar', 54);
insert into trains (model, capacity) values ('E-Series', 92);
insert into trains (model, capacity) values ('Club Wagon', 93);
insert into trains (model, capacity) values ('V40', 77);
insert into trains (model, capacity) values ('Esteem', 41);
insert into trains (model, capacity) values ('LeSabre', 18);
insert into trains (model, capacity) values ('Laser', 39);
insert into trains (model, capacity) values ('Pilot', 7);
insert into trains (model, capacity) values ('Forester', 97);
insert into trains (model, capacity) values ('LS', 59);
insert into trains (model, capacity) values ('XC70', 61);
insert into trains (model, capacity) values ('MX-6', 77);
insert into trains (model, capacity) values ('Corolla', 59);
insert into trains (model, capacity) values ('Town & Country', 15);
insert into trains (model, capacity) values ('Jetta III', 8);
insert into trains (model, capacity) values ('Firebird', 7);
insert into trains (model, capacity) values ('Genesis Coupe', 61);
insert into trains (model, capacity) values ('Laser', 4);
insert into trains (model, capacity) values ('I', 21);
insert into trains (model, capacity) values ('C-Class', 33);
insert into trains (model, capacity) values ('Mustang', 29);
insert into trains (model, capacity) values ('Cabriolet', 2);
insert into trains (model, capacity) values ('Electra', 29);
insert into trains (model, capacity) values ('Z8', 94);
insert into trains (model, capacity) values ('Sonata', 75);
insert into trains (model, capacity) values ('MX-5', 67);
insert into trains (model, capacity) values ('Countach', 93);
insert into trains (model, capacity) values ('Camaro', 45);
insert into trains (model, capacity) values ('Corvette', 7);
insert into trains (model, capacity) values ('Ram Van 1500', 88);
insert into trains (model, capacity) values ('Econoline E350', 97);
insert into trains (model, capacity) values ('Montero', 63);
insert into trains (model, capacity) values ('H1', 38);
insert into trains (model, capacity) values ('Tahoe', 3);
insert into trains (model, capacity) values ('XC90', 20);
insert into trains (model, capacity) values ('Miata MX-5', 34);
insert into trains (model, capacity) values ('A6', 79);
insert into trains (model, capacity) values ('Yukon XL 1500', 73);
insert into trains (model, capacity) values ('4Runner', 77);
insert into trains (model, capacity) values ('LX', 62);
insert into trains (model, capacity) values ('Journey', 71);
insert into trains (model, capacity) values ('Corvette', 60);
insert into trains (model, capacity) values ('Passport', 47);
insert into trains (model, capacity) values ('V70', 2);
insert into trains (model, capacity) values ('Eldorado', 85);
insert into trains (model, capacity) values ('E250', 3);
insert into trains (model, capacity) values ('FJ Cruiser', 59);
insert into trains (model, capacity) values ('Grand Am', 9);
insert into trains (model, capacity) values ('Element', 99);
insert into trains (model, capacity) values ('Shadow', 5);
insert into trains (model, capacity) values ('911', 38);
insert into trains (model, capacity) values ('Transit Connect', 49);
insert into trains (model, capacity) values ('Envoy XUV', 60);
insert into trains (model, capacity) values ('323', 61);
insert into trains (model, capacity) values ('Versa', 7);
insert into trains (model, capacity) values ('Ridgeline', 44);
insert into trains (model, capacity) values ('F250', 14);
insert into trains (model, capacity) values ('RAV4', 65);
insert into trains (model, capacity) values ('Sable', 20);
insert into trains (model, capacity) values ('Forester', 95);
insert into trains (model, capacity) values ('LeSabre', 5);
insert into trains (model, capacity) values ('Wrangler', 89);
insert into trains (model, capacity) values ('Riviera', 34);
insert into trains (model, capacity) values ('Brat', 61);
insert into trains (model, capacity) values ('Coachbuilder', 17);
insert into trains (model, capacity) values ('100', 92);
insert into trains (model, capacity) values ('RX', 83);
insert into trains (model, capacity) values ('SLK-Class', 46);
insert into trains (model, capacity) values ('626', 48);
insert into trains (model, capacity) values ('E350', 39);
insert into trains (model, capacity) values ('Odyssey', 47);
insert into trains (model, capacity) values ('Excel', 73);
insert into trains (model, capacity) values ('Quattroporte', 74);
insert into trains (model, capacity) values ('QX', 72);
insert into trains (model, capacity) values ('Grand Voyager', 22);
insert into trains (model, capacity) values ('Sunbird', 76);
insert into trains (model, capacity) values ('Allroad', 88);
insert into trains (model, capacity) values ('Sparrow', 94);
insert into trains (model, capacity) values ('Spectra', 73);
insert into trains (model, capacity) values ('Astro', 13);
insert into trains (model, capacity) values ('Rally Wagon 3500', 23);
insert into trains (model, capacity) values ('Terrain', 18);
insert into trains (model, capacity) values ('Accord', 49);
insert into trains (model, capacity) values ('Jetta', 31);
insert into trains (model, capacity) values ('Express 3500', 21);
insert into trains (model, capacity) values ('Accord', 2);
insert into trains (model, capacity) values ('2500', 100);
insert into trains (model, capacity) values ('Hombre Space', 98);
insert into trains (model, capacity) values ('Civic', 38);
insert into trains (model, capacity) values ('Envoy XL', 39);
insert into trains (model, capacity) values ('Vantage', 4);
insert into trains (model, capacity) values ('1500 Club Coupe', 56);
insert into trains (model, capacity) values ('Savana 2500', 48);
insert into trains (model, capacity) values ('W201', 96);
insert into trains (model, capacity) values ('Sunbird', 25);
insert into trains (model, capacity) values ('HHR', 99);
insert into trains (model, capacity) values ('Outback', 15);
insert into trains (model, capacity) values ('A6', 58);
insert into trains (model, capacity) values ('F-Series Super Duty', 47);
insert into trains (model, capacity) values ('300E', 72);
insert into trains (model, capacity) values ('RSX', 53);
insert into trains (model, capacity) values ('Thunderbird', 63);
insert into trains (model, capacity) values ('Fusion', 67);
insert into trains (model, capacity) values ('Mustang', 9);
insert into trains (model, capacity) values ('3 Series', 53);
insert into trains (model, capacity) values ('Grand Prix', 83);
insert into trains (model, capacity) values ('G-Series G20', 48);
insert into trains (model, capacity) values ('W201', 55);
insert into trains (model, capacity) values ('S4', 21);
insert into trains (model, capacity) values ('Mighty Max Macro', 78);
insert into trains (model, capacity) values ('MDX', 77);
insert into trains (model, capacity) values ('W126', 21);
insert into trains (model, capacity) values ('Xterra', 3);
insert into trains (model, capacity) values ('Land Cruiser', 51);
insert into trains (model, capacity) values ('911', 44);
insert into trains (model, capacity) values ('Envoy XL', 44);
insert into trains (model, capacity) values ('SLK-Class', 84);
insert into trains (model, capacity) values ('Sunbird', 24);
insert into trains (model, capacity) values ('Express 2500', 96);
insert into trains (model, capacity) values ('Regal', 74);
insert into trains (model, capacity) values ('CLK-Class', 17);
insert into trains (model, capacity) values ('430', 88);
insert into trains (model, capacity) values ('Mazda5', 76);
insert into trains (model, capacity) values ('Dakota', 3);
insert into trains (model, capacity) values ('Cavalier', 59);
insert into trains (model, capacity) values ('Firebird', 81);
insert into trains (model, capacity) values ('G', 52);
insert into trains (model, capacity) values ('LeSabre', 100);
insert into trains (model, capacity) values ('Scoupe', 43);
insert into trains (model, capacity) values ('Discovery', 99);
insert into trains (model, capacity) values ('Breeze', 74);
insert into trains (model, capacity) values ('Yaris', 93);
insert into trains (model, capacity) values ('Daewoo Kalos', 23);
insert into trains (model, capacity) values ('Acadia', 94);
insert into trains (model, capacity) values ('G', 19);
insert into trains (model, capacity) values ('B-Series', 68);
insert into trains (model, capacity) values ('Galant', 94);
insert into trains (model, capacity) values ('Accent', 49);
insert into trains (model, capacity) values ('RX', 57);
insert into trains (model, capacity) values ('S40', 49);
insert into trains (model, capacity) values ('Frontier', 90);
insert into trains (model, capacity) values ('Eclipse', 8);
insert into trains (model, capacity) values ('Ram Van 1500', 54);
insert into trains (model, capacity) values ('M', 78);
insert into trains (model, capacity) values ('Impreza', 18);
insert into trains (model, capacity) values ('7 Series', 60);
insert into trains (model, capacity) values ('XF', 36);
insert into trains (model, capacity) values ('HS', 43);
insert into trains (model, capacity) values ('Beretta', 98);
insert into trains (model, capacity) values ('Dynasty', 86);
insert into trains (model, capacity) values ('Amigo', 28);
insert into trains (model, capacity) values ('Elantra', 10);
insert into trains (model, capacity) values ('S10', 99);
insert into trains (model, capacity) values ('Accord', 66);
insert into trains (model, capacity) values ('Town Car', 6);
insert into trains (model, capacity) values ('Mighty Max', 13);
insert into trains (model, capacity) values ('Grand Marquis', 25);
insert into trains (model, capacity) values ('240SX', 8);
insert into trains (model, capacity) values ('Ram 3500', 32);
insert into trains (model, capacity) values ('Grand Caravan', 36);
insert into trains (model, capacity) values ('M Roadster', 47);
insert into trains (model, capacity) values ('Trooper', 26);
insert into trains (model, capacity) values ('Regency', 55);
insert into trains (model, capacity) values ('Previa', 19);
insert into trains (model, capacity) values ('Enclave', 16);
insert into trains (model, capacity) values ('E150', 18);
insert into trains (model, capacity) values ('80', 34);
insert into trains (model, capacity) values ('Dakota', 88);
insert into trains (model, capacity) values ('Envoy XUV', 35);
insert into trains (model, capacity) values ('Wrangler', 97);
insert into trains (model, capacity) values ('Corolla', 9);
insert into trains (model, capacity) values ('Ram Wagon B350', 82);
insert into trains (model, capacity) values ('Sprinter', 72);
insert into trains (model, capacity) values ('Familia', 6);
insert into trains (model, capacity) values ('Focus', 38);
insert into trains (model, capacity) values ('Boxster', 23);
insert into trains (model, capacity) values ('Ram 2500', 71);
insert into trains (model, capacity) values ('M Roadster', 2);
insert into trains (model, capacity) values ('G', 39);
insert into trains (model, capacity) values ('Freelander', 33);
insert into trains (model, capacity) values ('Montana', 87);
insert into trains (model, capacity) values ('New Yorker', 67);
insert into trains (model, capacity) values ('Miata MX-5', 12);
insert into trains (model, capacity) values ('Optima', 46);
insert into trains (model, capacity) values ('Highlander', 78);
insert into trains (model, capacity) values ('Grand Prix', 37);
insert into trains (model, capacity) values ('Fleetwood', 58);
insert into trains (model, capacity) values ('A3', 70);
insert into trains (model, capacity) values ('DeVille', 33);
insert into trains (model, capacity) values ('GX', 84);
insert into trains (model, capacity) values ('626', 84);
insert into trains (model, capacity) values ('E-Class', 25);
insert into trains (model, capacity) values ('Sentra', 92);
insert into trains (model, capacity) values ('A4', 29);
insert into trains (model, capacity) values ('Neon', 42);
insert into trains (model, capacity) values ('Savana 1500', 90);
insert into trains (model, capacity) values ('Town & Country', 27);
insert into trains (model, capacity) values ('F430', 52);
insert into trains (model, capacity) values ('F250', 66);
insert into trains (model, capacity) values ('Ram 3500', 2);
insert into trains (model, capacity) values ('Century', 71);
insert into trains (model, capacity) values ('Escort', 41);
insert into trains (model, capacity) values ('Ram', 100);
insert into trains (model, capacity) values ('350Z', 88);
insert into trains (model, capacity) values ('Diablo', 83);
insert into trains (model, capacity) values ('S4', 69);
insert into trains (model, capacity) values ('FX', 12);
insert into trains (model, capacity) values ('4Runner', 96);
insert into trains (model, capacity) values ('Intrepid', 55);
insert into trains (model, capacity) values ('Ram', 35);
insert into trains (model, capacity) values ('S4', 64);
insert into trains (model, capacity) values ('Tempest', 100);
insert into trains (model, capacity) values ('Grand Prix', 39);
insert into trains (model, capacity) values ('SLK-Class', 65);
insert into trains (model, capacity) values ('Grand Marquis', 92);
insert into trains (model, capacity) values ('3 Series', 12);
insert into trains (model, capacity) values ('Safari', 8);
insert into trains (model, capacity) values ('Econoline E150', 11);
insert into trains (model, capacity) values ('Ascender', 58);
insert into trains (model, capacity) values ('VehiCROSS', 36);
insert into trains (model, capacity) values ('Silverado 3500', 53);
insert into trains (model, capacity) values ('Avalanche', 93);
insert into trains (model, capacity) values ('350Z', 58);
insert into trains (model, capacity) values ('RVR', 1);
insert into trains (model, capacity) values ('CTS-V', 4);
insert into trains (model, capacity) values ('Sierra 1500', 26);
insert into trains (model, capacity) values ('Jimmy', 94);
insert into trains (model, capacity) values ('A8', 44);
insert into trains (model, capacity) values ('TT', 73);
insert into trains (model, capacity) values ('Entourage', 29);
insert into trains (model, capacity) values ('Acclaim', 63);
insert into trains (model, capacity) values ('CT', 29);
insert into trains (model, capacity) values ('Cavalier', 76);
insert into trains (model, capacity) values ('C70', 21);
insert into trains (model, capacity) values ('Boxster', 28);
insert into trains (model, capacity) values ('Grand Caravan', 18);
insert into trains (model, capacity) values ('Cabriolet', 32);
insert into trains (model, capacity) values ('911', 17);
insert into trains (model, capacity) values ('Cutlass Supreme', 82);
insert into trains (model, capacity) values ('SC', 16);
insert into trains (model, capacity) values ('IS', 84);
insert into trains (model, capacity) values ('GTO', 89);
insert into trains (model, capacity) values ('S-Class', 11);
insert into trains (model, capacity) values ('Grand Caravan', 26);
insert into trains (model, capacity) values ('G-Series 2500', 96);
insert into trains (model, capacity) values ('Camry', 60);
insert into trains (model, capacity) values ('Tracker', 21);
insert into trains (model, capacity) values ('Optima', 52);
insert into trains (model, capacity) values ('E150', 84);
insert into trains (model, capacity) values ('XK Series', 99);
insert into trains (model, capacity) values ('Galant', 85);
insert into trains (model, capacity) values ('Express 1500', 32);
insert into trains (model, capacity) values ('Mountaineer', 25);
insert into trains (model, capacity) values ('Civic', 76);
insert into trains (model, capacity) values ('Bonneville', 4);
insert into trains (model, capacity) values ('7 Series', 14);
insert into trains (model, capacity) values ('Escalade EXT', 52);
insert into trains (model, capacity) values ('Dakota', 30);
insert into trains (model, capacity) values ('Civic', 96);
insert into trains (model, capacity) values ('Astro', 32);
insert into trains (model, capacity) values ('Swift', 20);
insert into trains (model, capacity) values ('Tacoma Xtra', 9);
insert into trains (model, capacity) values ('CTS-V', 26);
insert into trains (model, capacity) values ('Mustang', 71);
insert into trains (model, capacity) values ('Odyssey', 31);
insert into trains (model, capacity) values ('IS', 88);
insert into trains (model, capacity) values ('Passat', 62);
insert into trains (model, capacity) values ('Cobalt SS', 25);
insert into trains (model, capacity) values ('2500 Club Coupe', 1);
insert into trains (model, capacity) values ('Cavalier', 34);
insert into trains (model, capacity) values ('i-Series', 23);
insert into trains (model, capacity) values ('Thunderbird', 65);
insert into trains (model, capacity) values ('Lumina', 33);
insert into trains (model, capacity) values ('Suburban 1500', 11);
insert into trains (model, capacity) values ('Santa Fe', 36);
insert into trains (model, capacity) values ('Frontier', 99);
insert into trains (model, capacity) values ('Justy', 7);
insert into trains (model, capacity) values ('Leone', 58);
insert into trains (model, capacity) values ('Focus', 14);
insert into trains (model, capacity) values ('Camaro', 92);
insert into trains (model, capacity) values ('LeSabre', 97);
insert into trains (model, capacity) values ('300SD', 47);
insert into trains (model, capacity) values ('Corvette', 57);
insert into trains (model, capacity) values ('Integra', 68);
insert into trains (model, capacity) values ('CR-V', 29);
insert into trains (model, capacity) values ('Grand Am', 89);
insert into trains (model, capacity) values ('G6', 52);
insert into trains (model, capacity) values ('Gran Sport', 72);
insert into trains (model, capacity) values ('300SE', 5);
insert into trains (model, capacity) values ('Frontier', 67);
insert into trains (model, capacity) values ('Cavalier', 29);
insert into trains (model, capacity) values ('A5', 34);
insert into trains (model, capacity) values ('Laser', 59);
insert into trains (model, capacity) values ('Allroad', 57);
insert into trains (model, capacity) values ('SC', 53);
insert into trains (model, capacity) values ('5000CS', 59);
insert into trains (model, capacity) values ('Enclave', 45);
insert into trains (model, capacity) values ('Sentra', 72);
insert into trains (model, capacity) values ('Avanti', 67);
insert into trains (model, capacity) values ('Sonata', 42);
insert into trains (model, capacity) values ('Armada', 16);
insert into trains (model, capacity) values ('E150', 77);
insert into trains (model, capacity) values ('Alcyone SVX', 39);
insert into trains (model, capacity) values ('Fit', 67);
insert into trains (model, capacity) values ('Sportvan G20', 51);
insert into trains (model, capacity) values ('MKX', 73);
insert into trains (model, capacity) values ('Century', 32);
insert into trains (model, capacity) values ('F350', 71);
insert into trains (model, capacity) values ('Tiburon', 60);
insert into trains (model, capacity) values ('Miata MX-5', 97);
insert into trains (model, capacity) values ('Crown Victoria', 72);
insert into trains (model, capacity) values ('E150', 14);
insert into trains (model, capacity) values ('X5', 77);
insert into trains (model, capacity) values ('Cordia', 29);
insert into trains (model, capacity) values ('FF', 26);
insert into trains (model, capacity) values ('Cavalier', 52);
insert into trains (model, capacity) values ('Challenger', 99);
insert into trains (model, capacity) values ('Golf', 8);
insert into trains (model, capacity) values ('Ram Wagon B350', 78);
insert into trains (model, capacity) values ('Entourage', 95);
insert into trains (model, capacity) values ('S5', 82);
insert into trains (model, capacity) values ('929', 36);
insert into trains (model, capacity) values ('Versa', 67);
insert into trains (model, capacity) values ('CTS', 2);
insert into trains (model, capacity) values ('B-Series Plus', 97);
insert into trains (model, capacity) values ('Passat', 24);
insert into trains (model, capacity) values ('Allante', 17);
insert into trains (model, capacity) values ('Protege', 24);
insert into trains (model, capacity) values ('Suburban 2500', 84);
insert into trains (model, capacity) values ('Sierra 2500', 68);
insert into trains (model, capacity) values ('Century', 61);
insert into trains (model, capacity) values ('Sienna', 13);
insert into trains (model, capacity) values ('Sprinter 3500', 88);
insert into trains (model, capacity) values ('Ranger', 81);
insert into trains (model, capacity) values ('Sierra', 99);
insert into trains (model, capacity) values ('Monte Carlo', 1);
insert into trains (model, capacity) values ('X6 M', 72);
insert into trains (model, capacity) values ('Continental GT', 37);
insert into trains (model, capacity) values ('4Runner', 69);
insert into trains (model, capacity) values ('Outback', 29);
insert into trains (model, capacity) values ('X5', 39);
insert into trains (model, capacity) values ('IPL G', 53);
insert into trains (model, capacity) values ('TL', 2);
insert into trains (model, capacity) values ('Yaris', 25);
insert into trains (model, capacity) values ('G-Series G30', 34);
insert into trains (model, capacity) values ('Neon', 94);
insert into trains (model, capacity) values ('Dynasty', 63);
insert into trains (model, capacity) values ('Hemisfear', 26);
insert into trains (model, capacity) values ('E150', 72);
insert into trains (model, capacity) values ('2500', 73);
insert into trains (model, capacity) values ('Tracer', 65);
insert into trains (model, capacity) values ('Z4 M', 52);
insert into trains (model, capacity) values ('Dakota', 4);
insert into trains (model, capacity) values ('Caprice', 69);
insert into trains (model, capacity) values ('Camaro', 84);
insert into trains (model, capacity) values ('Legacy', 6);
insert into trains (model, capacity) values ('D250 Club', 99);
insert into trains (model, capacity) values ('VS Commodore', 61);
insert into trains (model, capacity) values ('I', 1);
insert into trains (model, capacity) values ('V70', 17);
insert into trains (model, capacity) values ('SC', 56);
insert into trains (model, capacity) values ('Outlook', 51);
insert into trains (model, capacity) values ('525', 43);
insert into trains (model, capacity) values ('G-Series G30', 95);
insert into trains (model, capacity) values ('911', 83);
insert into trains (model, capacity) values ('Grand Marquis', 49);
insert into trains (model, capacity) values ('MPV', 7);
insert into trains (model, capacity) values ('LS', 93);
insert into trains (model, capacity) values ('300', 87);
insert into trains (model, capacity) values ('Touareg', 11);
insert into trains (model, capacity) values ('Savana 1500', 90);
insert into trains (model, capacity) values ('Z3', 40);
insert into trains (model, capacity) values ('Suburban 2500', 84);
insert into trains (model, capacity) values ('Expedition', 71);
insert into trains (model, capacity) values ('LTD Crown Victoria', 51);
insert into trains (model, capacity) values ('Sorento', 65);
insert into trains (model, capacity) values ('Genesis Coupe', 56);
insert into trains (model, capacity) values ('3500', 90);
insert into trains (model, capacity) values ('SC', 88);
insert into trains (model, capacity) values ('rio', 59);
insert into trains (model, capacity) values ('Protege', 49);
insert into trains (model, capacity) values ('Freelander', 28);
insert into trains (model, capacity) values ('Continental Flying Spur', 97);
insert into trains (model, capacity) values ('Endeavor', 32);
insert into trains (model, capacity) values ('M3', 23);
insert into trains (model, capacity) values ('928', 2);
insert into trains (model, capacity) values ('Murciélago', 78);
insert into trains (model, capacity) values ('LS', 90);
insert into trains (model, capacity) values ('Ram 1500 Club', 50);
insert into trains (model, capacity) values ('Accent', 35);
insert into trains (model, capacity) values ('M6', 67);
insert into trains (model, capacity) values ('Jimmy', 51);
insert into trains (model, capacity) values ('Ram 3500', 19);
insert into trains (model, capacity) values ('Corolla', 35);
insert into trains (model, capacity) values ('CT', 67);
insert into trains (model, capacity) values ('Mustang', 8);
insert into trains (model, capacity) values ('TT', 15);
insert into trains (model, capacity) values ('Solstice', 45);
insert into trains (model, capacity) values ('Defender', 32);
insert into trains (model, capacity) values ('Pilot', 89);
insert into trains (model, capacity) values ('Nitro', 66);
insert into trains (model, capacity) values ('S80', 99);
insert into trains (model, capacity) values ('Grand Caravan', 100);
insert into trains (model, capacity) values ('2500', 33);
insert into trains (model, capacity) values ('F150', 36);
insert into trains (model, capacity) values ('Silverado 3500', 84);
insert into trains (model, capacity) values ('Astra', 20);
insert into trains (model, capacity) values ('Sonoma', 99);
insert into trains (model, capacity) values ('Civic', 38);
insert into trains (model, capacity) values ('S-Class', 9);
insert into trains (model, capacity) values ('LS', 3);
insert into trains (model, capacity) values ('S-Series', 5);
insert into trains (model, capacity) values ('LHS', 14);
insert into trains (model, capacity) values ('Sephia', 89);
insert into trains (model, capacity) values ('A3', 56);
insert into trains (model, capacity) values ('F150', 11);
insert into trains (model, capacity) values ('Yukon XL 2500', 60);
insert into trains (model, capacity) values ('Altima', 66);
insert into trains (model, capacity) values ('Viper', 6);
insert into trains (model, capacity) values ('Ram 1500', 90);
insert into trains (model, capacity) values ('Sierra 3500HD', 69);
insert into trains (model, capacity) values ('Forester', 66);
insert into trains (model, capacity) values ('Grand Prix', 22);
insert into trains (model, capacity) values ('A6', 81);
insert into trains (model, capacity) values ('Suburban 1500', 96);
insert into trains (model, capacity) values ('300E', 91);
insert into trains (model, capacity) values ('Crossfire', 15);
insert into trains (model, capacity) values ('Altima', 51);
insert into trains (model, capacity) values ('Miata MX-5', 16);
insert into trains (model, capacity) values ('Tahoe', 56);
insert into trains (model, capacity) values ('Grand Am', 30);
insert into trains (model, capacity) values ('Laser', 84);
insert into trains (model, capacity) values ('1500 Club Coupe', 68);
insert into trains (model, capacity) values ('Diamante', 33);
insert into trains (model, capacity) values ('CLS-Class', 22);
insert into trains (model, capacity) values ('Riviera', 70);
insert into trains (model, capacity) values ('Grand Prix', 54);
insert into trains (model, capacity) values ('GL-Class', 77);
insert into trains (model, capacity) values ('Echo', 23);
insert into trains (model, capacity) values ('Miata MX-5', 40);
insert into trains (model, capacity) values ('Express 2500', 12);
insert into trains (model, capacity) values ('530', 48);
insert into trains (model, capacity) values ('Aura', 9);
insert into trains (model, capacity) values ('300SE', 77);
insert into trains (model, capacity) values ('Mustang', 99);
insert into trains (model, capacity) values ('88', 13);
insert into trains (model, capacity) values ('Excel', 41);
insert into trains (model, capacity) values ('Eldorado', 38);
insert into trains (model, capacity) values ('Crown Victoria', 42);
insert into trains (model, capacity) values ('Grand Am', 99);
insert into trains (model, capacity) values ('Mazda3', 58);
insert into trains (model, capacity) values ('Paseo', 62);
insert into trains (model, capacity) values ('MPV', 48);
insert into trains (model, capacity) values ('900', 65);
insert into trains (model, capacity) values ('Savana 2500', 73);
insert into trains (model, capacity) values ('XK Series', 85);
insert into trains (model, capacity) values ('Vanquish S', 45);
insert into trains (model, capacity) values ('Lancer Evolution', 97);
insert into trains (model, capacity) values ('Forester', 70);
insert into trains (model, capacity) values ('Coupe Quattro', 44);
insert into trains (model, capacity) values ('3500', 45);
insert into trains (model, capacity) values ('MX-5', 80);
insert into trains (model, capacity) values ('Ram Wagon B250', 30);
insert into trains (model, capacity) values ('V12 Vantage', 52);
insert into trains (model, capacity) values ('RL', 91);
insert into trains (model, capacity) values ('F-Series Super Duty', 50);
insert into trains (model, capacity) values ('Accord', 83);
insert into trains (model, capacity) values ('Sonata', 94);
insert into trains (model, capacity) values ('Sportvan G10', 11);
insert into trains (model, capacity) values ('RL', 84);
insert into trains (model, capacity) values ('E-Class', 49);
insert into trains (model, capacity) values ('Avalanche 1500', 60);
insert into trains (model, capacity) values ('G', 81);
insert into trains (model, capacity) values ('Mini Cooper S', 1);
insert into trains (model, capacity) values ('Rodeo', 83);
insert into trains (model, capacity) values ('Amigo', 35);
insert into trains (model, capacity) values ('Santa Fe', 65);
insert into trains (model, capacity) values ('Mazda5', 35);
insert into trains (model, capacity) values ('5000S', 40);
insert into trains (model, capacity) values ('Continental GTC', 70);
insert into trains (model, capacity) values ('Ram 3500 Club', 26);
insert into trains (model, capacity) values ('Tahoe', 19);
insert into trains (model, capacity) values ('Metro', 90);
insert into trains (model, capacity) values ('RSX', 77);
insert into trains (model, capacity) values ('E250', 1);
insert into trains (model, capacity) values ('S80', 94);
insert into trains (model, capacity) values ('Model S', 10);
insert into trains (model, capacity) values ('Lumina', 3);
insert into trains (model, capacity) values ('57', 44);
insert into trains (model, capacity) values ('Quest', 29);
insert into trains (model, capacity) values ('LS', 28);
insert into trains (model, capacity) values ('Camaro', 84);
insert into trains (model, capacity) values ('Sonata', 46);
insert into trains (model, capacity) values ('Echo', 95);
insert into trains (model, capacity) values ('Corolla', 62);
insert into trains (model, capacity) values ('Sorento', 83);
insert into trains (model, capacity) values ('Safari', 89);
insert into trains (model, capacity) values ('Metro', 91);
insert into trains (model, capacity) values ('Grand Prix', 60);
insert into trains (model, capacity) values ('G', 31);
insert into trains (model, capacity) values ('Savana 3500', 67);
insert into trains (model, capacity) values ('Envoy', 60);
insert into trains (model, capacity) values ('Coachbuilder', 70);
insert into trains (model, capacity) values ('Sebring', 72);
insert into trains (model, capacity) values ('Altima', 31);
insert into trains (model, capacity) values ('del Sol', 98);
insert into trains (model, capacity) values ('Corrado', 30);
insert into trains (model, capacity) values ('F350', 41);
insert into trains (model, capacity) values ('Azera', 98);
insert into trains (model, capacity) values ('S80', 36);
insert into trains (model, capacity) values ('Excursion', 10);
insert into trains (model, capacity) values ('Camry Solara', 32);
insert into trains (model, capacity) values ('CLK-Class', 1);
insert into trains (model, capacity) values ('Canyon', 66);
insert into trains (model, capacity) values ('Scoupe', 53);
insert into trains (model, capacity) values ('Monte Carlo', 20);
insert into trains (model, capacity) values ('Sentra', 73);
insert into trains (model, capacity) values ('Range Rover', 81);
insert into trains (model, capacity) values ('Civic', 48);
insert into trains (model, capacity) values ('300ZX', 72);
insert into trains (model, capacity) values ('Riviera', 90);
insert into trains (model, capacity) values ('Town Car', 62);
insert into trains (model, capacity) values ('Grand Caravan', 88);
insert into trains (model, capacity) values ('NX', 67);
insert into trains (model, capacity) values ('Touareg', 18);
insert into trains (model, capacity) values ('BRZ', 54);
insert into trains (model, capacity) values ('MX-5', 30);
insert into trains (model, capacity) values ('Probe', 75);
insert into trains (model, capacity) values ('E-Class', 44);
insert into trains (model, capacity) values ('2500', 26);
insert into trains (model, capacity) values ('SC', 46);
insert into trains (model, capacity) values ('Impala', 28);
insert into trains (model, capacity) values ('Mountaineer', 51);
insert into trains (model, capacity) values ('RX-8', 50);
insert into trains (model, capacity) values ('Town & Country', 44);
insert into trains (model, capacity) values ('Impala', 67);
insert into trains (model, capacity) values ('Avalon', 49);
insert into trains (model, capacity) values ('Sable', 74);
insert into trains (model, capacity) values ('Chariot', 70);
insert into trains (model, capacity) values ('Prius', 84);
insert into trains (model, capacity) values ('ES', 3);
insert into trains (model, capacity) values ('Continental', 99);
insert into trains (model, capacity) values ('Truck', 10);
insert into trains (model, capacity) values ('Forester', 26);
insert into trains (model, capacity) values ('Mustang', 30);
insert into trains (model, capacity) values ('Laser', 5);
insert into trains (model, capacity) values ('207', 54);
insert into trains (model, capacity) values ('Concorde', 38);
